"""PyInstaller spec file generation for ttkbootstrap projects."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ttkbootstrap.cli.config import TtkbConfig


# PyInstaller spec template that reads from ttkb.toml
SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for {app_name}.

This file is auto-generated by ttkbootstrap CLI.
Edit ttkb.toml to change build settings, then regenerate with:
    ttkb promote --pyinstaller --force
"""

import sys
from pathlib import Path

# PyInstaller exec's this spec with SPECPATH (directory of the .spec file)
# in the namespace. __file__ is not defined inside a spec.
PROJECT_ROOT = Path(SPECPATH).parent.parent
CONFIG_PATH = PROJECT_ROOT / "ttkb.toml"

# Ensure we can import ttkbootstrap CLI tools
try:
    from ttkbootstrap.cli.config import TtkbConfig
except ImportError:
    sys.path.insert(0, str(PROJECT_ROOT / "src"))
    from ttkbootstrap.cli.config import TtkbConfig

if not CONFIG_PATH.exists():
    raise FileNotFoundError(f"ttkb.toml not found at {{CONFIG_PATH}}")

config = TtkbConfig.load(CONFIG_PATH)

# Extract settings
APP_NAME = config.app.name
ENTRY_POINT = PROJECT_ROOT / config.app.entry
WINDOWED = config.build.windowed if config.build else True
ONEFILE = config.build.onefile if config.build else False

# Icon handling
ICON_PATH = None
if config.build and config.build.icon.path:
    icon_candidate = PROJECT_ROOT / config.build.icon.path
    if icon_candidate.exists():
        ICON_PATH = str(icon_candidate)
else:
    # Fall back to the bundled ttkbootstrap launch icon (the same artwork
    # the runtime sets via wm_iconphoto, just rendered as a multi-size
    # .ico for Windows). Users can override by setting [build.icon] path
    # in ttkb.toml.
    try:
        import ttkbootstrap
        default_icon = Path(ttkbootstrap.__file__).parent / "assets" / "ttkbootstrap.ico"
        if default_icon.exists():
            ICON_PATH = str(default_icon)
    except Exception:
        pass


# =============================================================================
# Collect data files
# =============================================================================

from glob import glob

datas = []

# Always include ttkb.toml
datas.append((str(CONFIG_PATH), "."))

# Include patterns from config
if config.build and config.build.datas.include:
    for pattern in config.build.datas.include:
        if pattern == "ttkb.toml":
            continue  # Already added
        matches = glob(str(PROJECT_ROOT / pattern), recursive=True)
        for match in matches:
            match_path = Path(match)
            if match_path.is_file():
                rel_path = match_path.relative_to(PROJECT_ROOT)
                dest_dir = str(rel_path.parent) if rel_path.parent != Path(".") else "."
                datas.append((str(match_path), dest_dir))


# =============================================================================
# Collect package data (themes, fonts, icon glyphmaps, locales, etc.)
# =============================================================================

# PyInstaller's collect_data_files walks a package and grabs every non-.py
# file, returning (src, dest) tuples in the form `datas` expects. We use it
# here for ttkbootstrap's own assets, plus a downstream workaround:
#
# WORKAROUND (until upstream fixes ship):
#   ttkbootstrap_icons ships a complete _pyinstaller/ hook directory, but
#   its pyproject.toml does not declare the `pyinstaller40` entry point, so
#   PyInstaller never discovers those hooks. ttkbootstrap_icons_bs also has
#   no hook of its own. Both manifest at runtime as:
#       ModuleNotFoundError: No module named 'ttkbootstrap_icons_bs.assets'
#   We bundle their data files manually here so frozen apps actually work.
#   Tracked at: https://github.com/israel-dryer/ttkbootstrap-icons/issues
#   Once upstream lands the entry point + a `hook-ttkbootstrap_icons_bs.py`,
#   the two icon-package entries below can be dropped — PyInstaller will
#   pick them up automatically.
from PyInstaller.utils.hooks import collect_data_files

for _pkg in ("ttkbootstrap", "ttkbootstrap_icons", "ttkbootstrap_icons_bs"):
    try:
        datas += collect_data_files(_pkg)
    except Exception as _e:  # pragma: no cover
        print(f"Warning: Could not collect data files from {{_pkg}}: {{_e}}")


# =============================================================================
# Hidden imports for ttkbootstrap
# =============================================================================

hiddenimports = [
    "ttkbootstrap",
    "ttkbootstrap.themes",
    "ttkbootstrap.style",
    "ttkbootstrap.widgets",
    "ttkbootstrap_icons",
    "ttkbootstrap_icons_bs",
    "PIL",
    "PIL._tkinter_finder",
    "babel.numbers",
    "babel.dates",
    "dateutil",
    "dateparser",
]

# babel.bin is a CLI script package whose __init__.py calls exit(1) when
# imported without args; PyInstaller's binary-dependency analyzer
# imports it during package walking and crashes. Excluding it is safe
# because nothing in a ttkbootstrap app uses babel's command-line tools.
excludes = [
    "babel.bin",
]


# =============================================================================
# Analysis
# =============================================================================

a = Analysis(
    [str(ENTRY_POINT)],
    pathex=[str(PROJECT_ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=excludes,
    noarchive=False,
    optimize=0,
)


# =============================================================================
# Build
# =============================================================================

pyz = PYZ(a.pure)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )

    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
'''


def generate_spec(
    config: TtkbConfig,
    project_root: Path,
    output_path: Path,
) -> None:
    """Generate a PyInstaller spec file.

    Args:
        config: The project configuration.
        project_root: Root directory of the project.
        output_path: Path to write the spec file.
    """
    content = SPEC_TEMPLATE.format(
        app_name=config.app.name,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
