"""PyInstaller spec file generation for ttkbootstrap projects."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ttkbootstrap.cli.config import TtkbConfig


# PyInstaller spec template that reads from ttkb.toml
SPEC_TEMPLATE = '''\
# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for {app_name}.

This file is auto-generated by ttkbootstrap CLI.
Edit ttkb.toml to change build settings, then regenerate with:
    ttkb promote --pyinstaller --force
"""

import sys
from pathlib import Path

# Ensure we can import ttkbootstrap CLI tools
try:
    from ttkbootstrap.cli.config import TtkbConfig
except ImportError:
    sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
    from ttkbootstrap.cli.config import TtkbConfig


# =============================================================================
# Load configuration from ttkb.toml
# =============================================================================

PROJECT_ROOT = Path(__file__).parent.parent.parent
CONFIG_PATH = PROJECT_ROOT / "ttkb.toml"

if not CONFIG_PATH.exists():
    raise FileNotFoundError(f"ttkb.toml not found at {{CONFIG_PATH}}")

config = TtkbConfig.load(CONFIG_PATH)

# Extract settings
APP_NAME = config.app.name
ENTRY_POINT = PROJECT_ROOT / config.app.entry
WINDOWED = config.build.windowed if config.build else True
ONEFILE = config.build.onefile if config.build else False

# Icon handling
ICON_PATH = None
if config.build and config.build.icon.path:
    icon_candidate = PROJECT_ROOT / config.build.icon.path
    if icon_candidate.exists():
        ICON_PATH = str(icon_candidate)
else:
    # Try default ttkbootstrap icon
    try:
        import ttkbootstrap
        default_icon = Path(ttkbootstrap.__file__).parent / "assets" / "icons" / "app.ico"
        if default_icon.exists():
            ICON_PATH = str(default_icon)
    except Exception:
        pass


# =============================================================================
# Collect data files
# =============================================================================

from glob import glob

datas = []

# Always include ttkb.toml
datas.append((str(CONFIG_PATH), "."))

# Include patterns from config
if config.build and config.build.datas.include:
    for pattern in config.build.datas.include:
        if pattern == "ttkb.toml":
            continue  # Already added
        matches = glob(str(PROJECT_ROOT / pattern), recursive=True)
        for match in matches:
            match_path = Path(match)
            if match_path.is_file():
                rel_path = match_path.relative_to(PROJECT_ROOT)
                dest_dir = str(rel_path.parent) if rel_path.parent != Path(".") else "."
                datas.append((str(match_path), dest_dir))


# =============================================================================
# Collect ttkbootstrap assets
# =============================================================================

try:
    import ttkbootstrap
    ttkb_path = Path(ttkbootstrap.__file__).parent

    # Include ttkbootstrap themes
    themes_dir = ttkb_path / "themes"
    if themes_dir.exists():
        for theme_file in themes_dir.glob("*.json"):
            datas.append((str(theme_file), "ttkbootstrap/themes"))

    # Include ttkbootstrap assets
    assets_dir = ttkb_path / "assets"
    if assets_dir.exists():
        for asset_file in assets_dir.rglob("*"):
            if asset_file.is_file():
                rel = asset_file.relative_to(ttkb_path)
                datas.append((str(asset_file), str(Path("ttkbootstrap") / rel.parent)))

except Exception as e:
    print(f"Warning: Could not collect ttkbootstrap assets: {{e}}")


# =============================================================================
# Hidden imports for ttkbootstrap
# =============================================================================

hiddenimports = [
    "ttkbootstrap",
    "ttkbootstrap.themes",
    "ttkbootstrap.style",
    "ttkbootstrap.widgets",
    "PIL",
    "PIL._tkinter_finder",
    "babel",
    "babel.numbers",
    "babel.dates",
    "dateutil",
    "dateparser",
]


# =============================================================================
# Analysis
# =============================================================================

a = Analysis(
    [str(ENTRY_POINT)],
    pathex=[str(PROJECT_ROOT / "src")],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)


# =============================================================================
# Build
# =============================================================================

pyz = PYZ(a.pure)

if ONEFILE:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.datas,
        [],
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        upx_exclude=[],
        runtime_tmpdir=None,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )
else:
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name=APP_NAME,
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=True,
        console=not WINDOWED,
        disable_windowed_traceback=False,
        argv_emulation=False,
        target_arch=None,
        codesign_identity=None,
        entitlements_file=None,
        icon=ICON_PATH,
    )

    coll = COLLECT(
        exe,
        a.binaries,
        a.datas,
        strip=False,
        upx=True,
        upx_exclude=[],
        name=APP_NAME,
    )
'''


def generate_spec(
    config: TtkbConfig,
    project_root: Path,
    output_path: Path,
) -> None:
    """Generate a PyInstaller spec file.

    Args:
        config: The project configuration.
        project_root: Root directory of the project.
        output_path: Path to write the spec file.
    """
    content = SPEC_TEMPLATE.format(
        app_name=config.app.name,
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
