STANDARD_THEMES = {
    "cosmo": {
        "dark": False,
        "colors": {
            "primary": "#2780e3",
            "secondary": "#7E8081",
            "success": "#3fb618",
            "info": "#9954bb",
            "warning": "#ff7518",
            "danger": "#ff0039",
            "light": "#F8F9FA",
            "dark": "#373A3C",
            "background": "#ffffff",
            "foreground": "#373a3c",
            "select_background": "#7e8081",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#373a3c",
            "input_background": "#fdfdfe",
            "active": "#efefef",
        },
    },
    "flatly": {
        "dark": False,
        "colors": {
            "primary": "#2c3e50",
            "secondary": "#95a5a6",
            "success": "#18bc9c",
            "info": "#3498db",
            "warning": "#f39c12",
            "danger": "#e74c3c",
            "light": "#ECF0F1",
            "dark": "#7B8A8B",
            "background": "#ffffff",
            "foreground": "#212529",
            "select_background": "#95a5a6",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#212529",
            "input_background": "#ffffff",
            "active": "#e2e2e2",
        },
    },
    "litera": {
        "dark": False,
        "colors": {
            "primary": "#4582ec",
            "secondary": "#adb5bd",
            "success": "#02b875",
            "info": "#17a2b8",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#F8F9FA",
            "dark": "#343A40",
            "background": "#ffffff",
            "foreground": "#343a40",
            "select_background": "#adb5bd",
            "select_foreground": "#ffffff",
            "border": "#bfbfbf",
            "input_foreground": "#343a40",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "minty": {
        "dark": False,
        "colors": {
            "primary": "#78c2ad",
            "secondary": "#f3969a",
            "success": "#56cc9d",
            "info": "#6cc3d5",
            "warning": "#ffce67",
            "danger": "#ff7851",
            "light": "#F8F9FA",
            "dark": "#343A40",
            "background": "#ffffff",
            "foreground": "#5a5a5a",
            "select_background": "#f3969a",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#696969",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "lumen": {
        "dark": False,
        "colors": {
            "primary": "#158cba",
            "secondary": "#919191",
            "success": "#28b62c",
            "info": "#75caeb",
            "warning": "#ff851b",
            "danger": "#ff4136",
            "light": "#F6F6F6",
            "dark": "#555555",
            "background": "#ffffff",
            "foreground": "#555555",
            "select_background": "#919191",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#555555",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "sandstone": {
        "dark": False,
        "colors": {
            "primary": "#325D88",
            "secondary": "#8e8c84",
            "success": "#93c54b",
            "info": "#29abe0",
            "warning": "#f47c3c",
            "danger": "#d9534f",
            "light": "#F8F5F0",
            "dark": "#3E3F3A",
            "background": "#ffffff",
            "foreground": "#3e3f3a",
            "select_background": "#8e8c84",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#6E6D69",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "yeti": {
        "dark": False,
        "colors": {
            "primary": "#008cba",
            "secondary": "#707070",
            "success": "#43ac6a",
            "info": "#5bc0de",
            "warning": "#e99002",
            "danger": "#f04124",
            "light": "#EEEEEE",
            "dark": "#222222",
            "background": "#ffffff",
            "foreground": "#222222",
            "select_background": "#707070",
            "select_foreground": "#ffffff",
            "border": "#cccccc",
            "input_foreground": "#222222",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "pulse": {
        "dark": False,
        "colors": {
            "primary": "#593196",
            "secondary": "#69676E",
            "success": "#13b955",
            "info": "#009cdc",
            "warning": "#efa31d",
            "danger": "#fc3939",
            "light": "#F9F8FC",
            "dark": "#17141F",
            "background": "#ffffff",
            "foreground": "#444444",
            "select_background": "#69676e",
            "select_foreground": "#ffffff",
            "border": "#cbc8d0",
            "input_foreground": "#444444",
            "input_background": "#fdfdfe",
            "active": "#e5e5e5",
        },
    },
    "united": {
        "dark": False,
        "colors": {
            "primary": "#e95420",
            "secondary": "#aea79f",
            "success": "#38b44a",
            "info": "#17a2b8",
            "warning": "#efb73e",
            "danger": "#df382c",
            "light": "#E9ECEF",
            "dark": "#772953",
            "background": "#ffffff",
            "foreground": "#333333",
            "select_background": "#aea79f",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#333333",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "morph": {
        "dark": False,
        "colors": {
            "primary": "#378DFC",
            "secondary": "#aaaaaa",
            "success": "#43cc29",
            "info": "#5B62F4",
            "warning": "#FFC107",
            "danger": "#E52527",
            "light": "#F0F5FA",
            "dark": "#212529",
            "background": "#D9E3F1",
            "foreground": "#7B8AB8",
            "select_background": "#aaaaaa",
            "select_foreground": "#FBFDFF",
            "border": "#B9C7DA",
            "input_foreground": "#7F8EBA",
            "input_background": "#F0F5FA",
            "active": "#C3CCD8",
        },
    },
    "journal": {
        "dark": False,
        "colors": {
            "primary": "#eb6864",
            "secondary": "#aaaaaa",
            "success": "#22b24c",
            "info": "#336699",
            "warning": "#f5e625",
            "danger": "#f57a00",
            "light": "#F8F9FA",
            "dark": "#222222",
            "background": "#ffffff",
            "foreground": "#222222",
            "select_background": "#aaaaaa",
            "select_foreground": "#ffffff",
            "border": "#ced4da",
            "input_foreground": "#565656",
            "input_background": "#fff",
            "active": "#e5e5e5",
        },
    },
    "darkly": {
        "dark": True,
        "colors": {
            "primary": "#375a7f",
            "secondary": "#444444",
            "success": "#00bc8c",
            "info": "#3498db",
            "warning": "#f39c12",
            "danger": "#e74c3c",
            "light": "#ADB5BD",
            "dark": "#303030",
            "background": "#222222",
            "foreground": "#ffffff",
            "select_background": "#555555",
            "select_foreground": "#ffffff",
            "border": "#222222",
            "input_foreground": "#ffffff",
            "input_background": "#2f2f2f",
            "active": "#1F1F1F",
        },
    },
    "superhero": {
        "dark": True,
        "colors": {
            "primary": "#4c9be8",
            "secondary": "#4e5d6c",
            "success": "#5cb85c",
            "info": "#5bc0de",
            "warning": "#f0ad4e",
            "danger": "#d9534f",
            "light": "#ABB6C2",
            "dark": "#20374C",
            "background": "#2b3e50",
            "foreground": "#ffffff",
            "select_background": "#526170",
            "select_foreground": "#ffffff",
            "border": "#222222",
            "input_foreground": "#ebebeb",
            "input_background": "#32465a",
            "active": "#2B4155",
        },
    },
    "solar": {
        "dark": True,
        "colors": {
            "primary": "#bc951a",
            "secondary": "#94a2a4",
            "success": "#44aca4",
            "info": "#3f98d7",
            "warning": "#d05e2f",
            "danger": "#d95092",
            "light": "#A9BDBD",
            "dark": "#073642",
            "background": "#002B36",
            "foreground": "#ffffff",
            "select_background": "#0b5162",
            "select_foreground": "#ffffff",
            "border": "#00252e",
            "input_foreground": "#A9BDBD",
            "input_background": "#073642",
            "active": "#002730",
        },
    },
    "cyborg": {
        "dark": True,
        "colors": {
            "primary": "#2a9fd6",
            "secondary": "#555555",
            "success": "#77b300",
            "info": "#9933cc",
            "warning": "#ff8800",
            "danger": "#cc0000",
            "light": "#ADAFAE",
            "dark": "#222222",
            "background": "#060606",
            "foreground": "#ffffff",
            "select_background": "#454545",
            "select_foreground": "#ffffff",
            "border": "#060606",
            "input_foreground": "#ffffff",
            "input_background": "#191919",
            "active": "#282828",
        },
    },
    "vapor": {
        "dark": True,
        "colors": {
            "primary": "#6e40c0",
            "secondary": "#ea38b8",
            "success": "#3af180",
            "info": "#1da2f2",
            "warning": "#ffbd05",
            "danger": "#e34b54",
            "light": "#44d7e8",
            "dark": "#170229",
            "background": "#190831",
            "foreground": "#32fbe2",
            "select_background": "#461a8a",
            "select_foreground": "#ffffff",
            "border": "#060606",
            "input_foreground": "#bfb6cd",
            "input_background": "#30115e",
            "active": "#17082E",
        },
    },
    "simplex": {
        "dark": False,
        "colors": {
            "primary": "#d8220e",
            "secondary": "#858e96",
            "success": "#469307",
            "info": "#0099ce",
            "warning": "#d88220",
            "danger": "#9a479e",
            "light": "#f2f2f2",
            "dark": "#3b3d3f",
            "background": "#fcfcfc",
            "foreground": "#3b3d3f",
            "select_background": "#a9afb6",
            "select_foreground": "#ffffff",
            "border": "#858e96",
            "input_foreground": "#3b3d3f",
            "input_background": "#fcfcfc",
            "active": "#e2e2e2",
        },
    },
    "cerculean": {
        "dark": False,
        "colors": {
            "primary": "#4bb1ea",
            "secondary": "#a9b4be",
            "success": "#84b251",
            "info": "#225384",
            "warning": "#e16e25",
            "danger": "#cf3c40",
            "light": "#eceef1",
            "dark": "#33383e",
            "background": "#ffffff",
            "foreground": "#2ea4e7",
            "select_background": "#adb5bd",
            "select_foreground": "#ffffff",
            "border": "#a9b4be",
            "input_foreground": "#495057",
            "input_background": "#ffffff",
            "active": "#e5e5e5",
        },
    },
}
