"""Legacy 16-key theme adapter and the opt-in `install_legacy_themes()`.

The pre-2.0 catalog authored each theme as a flat 16-key `colors` dict. 2.0
ships a curated semantic-anchor catalog instead (`themes/builtin.py`); the old
names are available on demand via `install_legacy_themes()`.

This module is the **only** place the 16-key shape is understood (Workstream F's
compat-quarantine discipline). Legacy themes keep their authored accents,
background/foreground, and selection colors verbatim -- only the inconsistent,
contrast-buggy plumbing (`border`, `inputbg`, `active`) is regenerated by the
same surface derivation the curated catalog uses. So an old theme stays
recognizable but sheds its worst plumbing bugs.
"""
import warnings

from ttkbootstrap.style.theme import (
    Colors,
    ThemeDefinition,
    _ACTIVE_MIX,
    _ACTIVE_MIX_D,
    _INPUT_LIFT,
    _border_color,
    _darken_color,
    _lighten_color,
    _normalize_color,
)
from ttkbootstrap.themes.standard import STANDARD_THEMES


def theme_from_legacy_dict(name, spec) -> ThemeDefinition:
    """Adapt a legacy ``{'type', 'colors': {16 keys}}`` spec into a resolved
    `ThemeDefinition`.

    Authored accents, `bg`/`fg`, `selectbg`/`selectfg`, and the `light`/`dark`
    accents are preserved; `border`, `inputbg`, and `active` are regenerated
    from `bg` with the mode-aware, hue-preserving surface derivation.

    Parameters:
        name: Theme name to assign.
        spec: Legacy spec, `{'type': 'light'|'dark', 'colors': {16 keys}}`.

    Returns:
        ThemeDefinition: The resolved theme definition.
    """
    c = spec["colors"]
    mode = spec["type"]
    bg = _normalize_color(c["bg"])
    border = _border_color(bg)
    if mode == "dark":
        inputbg = _lighten_color(bg, _INPUT_LIFT)
        active = _lighten_color(bg, _ACTIVE_MIX_D)
    else:
        inputbg = bg
        active = _darken_color(bg, _ACTIVE_MIX)
    colors = Colors(
        primary=c["primary"],
        secondary=c["secondary"],
        success=c["success"],
        info=c["info"],
        warning=c["warning"],
        danger=c["danger"],
        light=c["light"],
        dark=c["dark"],
        bg=c["bg"],
        fg=c["fg"],
        selectbg=c["selectbg"],
        selectfg=c["selectfg"],
        border=border,
        inputfg=c["inputfg"],
        inputbg=inputbg,
        active=active,
    )
    return ThemeDefinition(name=name, colors=colors, themetype=mode)


def install_legacy_themes(style=None) -> None:
    """Register the pre-2.0 theme names on the live `Style` (opt-in).

    Each legacy theme is adapted through `theme_from_legacy_dict` (authored
    identity preserved, plumbing regenerated). Already-registered names are
    skipped, so calling this more than once is safe. Emits a one-time
    `DeprecationWarning`: the legacy names are a migration convenience, not the
    2.0 catalog.

    Parameters:
        style: The `Style` to register onto; defaults to the live singleton.
    """
    if style is None:
        # local import breaks the themes<-engine import cycle
        from ttkbootstrap.style.engine import Style

        style = Style.get_instance()
        if style is None:
            raise RuntimeError(
                "No Style instance yet; create an App/Style before calling "
                "install_legacy_themes()."
            )
    warnings.warn(
        "Legacy (pre-2.0) theme names are a migration convenience and are "
        "planned for removal in 3.0; prefer the 2.0 catalog "
        "(Style.theme_names()).",
        DeprecationWarning,
        stacklevel=2,
    )
    for name, spec in STANDARD_THEMES.items():
        if name in style._theme_names:
            continue
        style.register_theme(theme_from_legacy_dict(name, spec))
