#!/usr/bin/env python
"""Generate the canonical bootstyle reference from the vocabulary + registry.

The bootstyle grammar (2.0 Workstream D) has a single closed vocabulary
(`ttkbootstrap.constants`) and a frozen builder registry
(`ttkbootstrap.style.builders.registry`) that together define exactly which
canonical bootstyle strings resolve to a real ttk style. Rather than hand-list
them (and drift), this tool derives them:

- `canonical_bootstyles()` -> the sorted set of canonical strings a user can
  type. It backs the `BootStyle` `Literal` in `constants.py` (regenerate the
  block below and paste it in) and the `test_bootstyle_grammar` sync test.
- `reference_table_markdown()` -> the human reference grouped by widget family,
  written to `development/2_0_bootstyle_reference.md` (the Workstream-H docs
  source; kept under `development/` so it survives the docs transition).

Run it after changing the vocabulary or adding/removing a builder:

    python tools/generate_bootstyle_reference.py

It rewrites the markdown file and prints the `BootStyle = Literal[...]` block to
stdout for pasting into `constants.py`. The sync test fails until both are
regenerated, so the reference can never silently drift from the code.
"""
from __future__ import annotations

import sys
from pathlib import Path

_SRC = Path(__file__).resolve().parent.parent / "src"
if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))

from ttkbootstrap.constants import (  # noqa: E402
    BOOTSTYLE_COLORS,
    BOOTSTYLE_BASES,
    BOOTSTYLE_INTERNAL_MODIFIERS,
    NEUTRAL,
    NEUTRAL_FAMILIES,
)
from ttkbootstrap.style.builders import load_builders  # noqa: E402
from ttkbootstrap.style.builders.registry import (  # noqa: E402
    builder_keys,
    DEFAULT_VARIANT,
)

_REFERENCE_MD = (
    Path(__file__).resolve().parent.parent
    / "development"
    / "2_0_bootstyle_reference.md"
)


def _public_keys():
    """Return the registered (variant, family) keys that are user-facing.

    The internal composite variants (`meter`/`metersubtxt`/`date`/`table`) are
    plumbing for Meter/DateEntry/Tableview -- never typed by a user -- so they
    are excluded from the public reference.
    """
    load_builders()
    return sorted(
        (variant, family)
        for variant, family in builder_keys()
        if variant not in BOOTSTYLE_INTERNAL_MODIFIERS
    )


def _strings_for_key(variant, family):
    """Yield the canonical bootstyle strings a user types for one key.

    The base-type is spelled only for the "chameleon" families (`toggle`,
    `toolbutton`); for every other family it is inferred from the widget, so it
    is omitted. Slots are emitted in canonical order: color, modifier, base.
    """
    modifier = None if variant == DEFAULT_VARIANT else variant
    base = family if family in BOOTSTYLE_BASES else None
    for color in (None, *BOOTSTYLE_COLORS):
        # `neutral` is a derived, no-accent color that only renders for a curated
        # set of families (NEUTRAL_FAMILIES) -- don't advertise it elsewhere even
        # though the tokenizer would parse it.
        if color == NEUTRAL and family not in NEUTRAL_FAMILIES:
            continue
        parts = [p for p in (color, modifier, base) if p]
        if parts:
            yield "-".join(parts)


def canonical_bootstyles():
    """Return the sorted set of all canonical bootstyle strings."""
    strings = set()
    for variant, family in _public_keys():
        strings.update(_strings_for_key(variant, family))
    return sorted(strings)


def bootstyle_literal_source():
    """Return the `BootStyle = Literal[...]` source block for constants.py."""
    entries = ",\n    ".join(repr(s) for s in canonical_bootstyles())
    return f"BootStyle = Literal[\n    {entries},\n]\n"


def reference_table_markdown():
    """Return the canonical bootstyle reference as a markdown document."""
    lines = [
        "# Bootstyle reference (generated)",
        "",
        "> Generated by `tools/generate_bootstyle_reference.py` from the closed",
        "> vocabulary (`ttkbootstrap.constants`) and the builder registry. Do",
        "> **not** edit by hand -- regenerate after any vocabulary/builder",
        "> change. Source for the Workstream-H docs.",
        "",
        "## Grammar",
        "",
        "A bootstyle is `[color-][modifier-]<base-type>[-orient]`, with exactly",
        "one token per slot in that order. The **base-type** is normally",
        "inferred from the widget and only spelled for the chameleon families",
        "`toggle`/`toolbutton`. Unknown tokens fail loudly (a warning by",
        "default; `set_bootstyle_strict(True)` or `TTKBOOTSTRAP_STRICT=1` raises).",
        "",
        "## Colors",
        "",
        ", ".join(f"`{c}`" for c in BOOTSTYLE_COLORS),
        "",
        "## Widget families and variants",
        "",
        "| Widget family | Variant | Example |",
        "| --- | --- | --- |",
    ]
    for variant, family in _public_keys():
        example = _example_for_key(variant, family)
        variant_label = "default" if variant == DEFAULT_VARIANT else variant
        lines.append(f"| `{family}` | `{variant_label}` | `{example}` |")
    lines.append("")
    return "\n".join(lines)


def _example_for_key(variant, family):
    """A single representative canonical string for the reference table."""
    modifier = None if variant == DEFAULT_VARIANT else variant
    base = family if family in BOOTSTYLE_BASES else None
    parts = [p for p in ("primary", modifier, base) if p]
    return "-".join(parts)


def main():
    _REFERENCE_MD.write_text(reference_table_markdown() + "\n", encoding="utf-8")
    print(f"wrote {_REFERENCE_MD}")
    print()
    print("# paste this BootStyle block into src/ttkbootstrap/constants.py:")
    print(bootstyle_literal_source())


if __name__ == "__main__":
    main()
