"""Type stubs for ttkbootstrap's public API.

GENERATED by `tools/generate_widget_stubs.py` from the widget reference pages
under `docs/reference/api/`. Do not edit by hand -- run the generator instead;
`tests/test_widget_stubs.py` enforces that this file matches.

The concrete widget classes below get an explicit constructor so editors and
type checkers can see each widget's options. At runtime they are the one-line
subclasses in `__init__.py`, whose shared mixin constructor is generic.
"""
from __future__ import annotations

from datetime import date, datetime
from tkinter import Misc, Variable, PhotoImage
from tkinter.font import Font
from typing import Any, Callable

from ttkbootstrap.style import AutoStyleMixin as AutoStyleMixin, BootMixin as BootMixin

from tkinter import Canvas as _tkinterCanvas
from tkinter import Frame as _tkinterFrame
from tkinter import Label as _tkinterLabel
from tkinter import Listbox as _tkinterListbox
from tkinter import Menu as _tkinterMenu
from tkinter import Text as _tkinterText
from tkinter import Tk as _tkinterTk
from tkinter.ttk import Button as _ttkButton
from tkinter.ttk import Checkbutton as _ttkCheckbutton
from tkinter.ttk import Combobox as _ttkCombobox
from tkinter.ttk import Entry as _ttkEntry
from tkinter.ttk import Frame as _ttkFrame
from tkinter.ttk import Label as _ttkLabel
from tkinter.ttk import Labelframe as _ttkLabelframe
from tkinter.ttk import Menubutton as _ttkMenubutton
from tkinter.ttk import Notebook as _ttkNotebook
from tkinter.ttk import OptionMenu as _ttkOptionMenu
from tkinter.ttk import Panedwindow as _ttkPanedwindow
from tkinter.ttk import Progressbar as _ttkProgressbar
from tkinter.ttk import Radiobutton as _ttkRadiobutton
from tkinter.ttk import Scale as _ttkScale
from tkinter.ttk import Scrollbar as _ttkScrollbar
from tkinter.ttk import Separator as _ttkSeparator
from tkinter.ttk import Sizegrip as _ttkSizegrip
from tkinter.ttk import Spinbox as _ttkSpinbox
from tkinter.ttk import Treeview as _ttkTreeview

from tkinter import (
    BooleanVar as BooleanVar,
    DoubleVar as DoubleVar,
    IntVar as IntVar,
    PhotoImage as PhotoImage,
    StringVar as StringVar,
    Variable as Variable,
    filedialog as filedialog,
)
from tkinter.font import (
    Font as Font,
    families as font_families,
    nametofont as nametofont,
)
from ttkbootstrap.dialogs import (
    ColorChooser as ColorChooser,
    ColorChooserDialog as ColorChooserDialog,
    ColorDropperDialog as ColorDropperDialog,
    DatePickerDialog as DatePickerDialog,
    Dialog as Dialog,
    FontDialog as FontDialog,
    MessageDialog as MessageDialog,
    Messagebox as Messagebox,
    QueryDialog as QueryDialog,
    Querybox as Querybox,
)
from ttkbootstrap.localization import (
    L as L,
    LocaleVar as LocaleVar,
    set_locale as set_locale,
)
from ttkbootstrap.style import (
    Assets as Assets,
    AutoStyleMixin as AutoStyleMixin,
    BootMixin as BootMixin,
    Bootstyle as Bootstyle,
    El as El,
    FluentGeometryMixin as FluentGeometryMixin,
    Icon as Icon,
    Style as Style,
    StyleName as StyleName,
    Theme as Theme,
    apply_bootstyle as apply_bootstyle,
    apply_icon as apply_icon,
    bootify as bootify,
    enable_global_api as enable_global_api,
    icon_element as icon_element,
    image_element as image_element,
    is_bootstyle_strict as is_bootstyle_strict,
    layout as layout,
    register_style as register_style,
    set_bootstyle_strict as set_bootstyle_strict,
    state_map as state_map,
    statespec as statespec,
)
from ttkbootstrap.themes.legacy import install_legacy_themes as install_legacy_themes
from ttkbootstrap.utils import (
    Fonts as Fonts,
    color_to_hex as color_to_hex,
    color_to_hsl as color_to_hsl,
    color_to_rgb as color_to_rgb,
    conform_color_model as conform_color_model,
    contrast_color as contrast_color,
    enable_high_dpi_awareness as enable_high_dpi_awareness,
    on_theme_change as on_theme_change,
    remove_theme_change_callback as remove_theme_change_callback,
    scale_size as scale_size,
    set_default_button as set_default_button,
    set_global_family as set_global_family,
    theme_aware as theme_aware,
    update_hsl_value as update_hsl_value,
    windowing_system as windowing_system,
)
from ttkbootstrap.validation import (
    Validation as Validation,
    ValidationEvent as ValidationEvent,
    validator as validator,
)
from ttkbootstrap.widgets import (
    DateEntry as DateEntry,
    Floodgauge as Floodgauge,
    FloodgaugeLegacy as FloodgaugeLegacy,
    LabeledScale as LabeledScale,
    M as M,
    Meter as Meter,
    ScrolledFrame as ScrolledFrame,
    ScrolledText as ScrolledText,
    TableColumn as TableColumn,
    TableRow as TableRow,
    Tableview as Tableview,
    ToastNotification as ToastNotification,
    ToolTip as ToolTip,
)
from ttkbootstrap.window import App as App, Toplevel as Toplevel, Window as Window


class Tk(AutoStyleMixin, _tkinterTk):
    """Tk is tkinter's classic root window (tk.Tk), themed by ttkbootstrap and re-exported as ttk.Tk. It is the main window of an application and the top of the widget tree; creating it also starts the Tcl/Tk interpreter."""
    def __init__(
        self,
        screenName: str | None = ...,
        baseName: str | None = ...,
        className: str = ...,
        useTk: bool = ...,
        sync: bool = ...,
        use: str | None = ...,
        *,
        autostyle: bool = ...,
    ) -> None:
        """Tk is tkinter's classic root window (tk.Tk), themed by ttkbootstrap and re-exported as ttk.Tk. It is the main window of an application and the top of the widget tree; creating it also starts the Tcl/Tk interpreter.

        Args:
            screenName: The X display to open the window on.
            baseName: The base for the profile file name.
            className: The widget class of the root window.
            useTk: Whether to initialize the Tk subsystem.
            sync: Whether to execute X server commands synchronously.
            use: The window id to embed this interpreter into.
            autostyle: Constructor only. True (default) applies the active theme; False opts out.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        menu: Menu = ...,
        background: str = ...,
        bg: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        padx: int = ...,
        pady: int = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
    ) -> Any: ...
    config = configure

class Menu(AutoStyleMixin, _tkinterMenu):
    """Menu is tkinter's menu widget (tk.Menu), themed by ttkbootstrap and re-exported as ttk.Menu. It backs menu bars, cascading submenus, and right-click context menus; ttkbootstrap adds helpers for the native macOS application menu. Entries are addressed by integer index (0-based) or the special index "end" / "active" / "last"."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        activeforeground: str = ...,
        activebackground: str = ...,
        activeborderwidth: int = ...,
        disabledforeground: str = ...,
        selectcolor: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        tearoff: bool = ...,
        tearoffcommand: Callable[..., Any] = ...,
        postcommand: Callable[..., Any] = ...,
        title: str = ...,
        type: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
    ) -> None:
        """Menu is tkinter's menu widget (tk.Menu), themed by ttkbootstrap and re-exported as ttk.Menu. It backs menu bars, cascading submenus, and right-click context menus; ttkbootstrap adds helpers for the native macOS application menu. Entries are addressed by integer index (0-based) or the special index "end" / "active" / "last".

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (default) paints the menu with the active theme and repaints on a theme switch; False opts out.
            font: The font for entry labels.
            foreground (fg): The text color of entries.
            background (bg): The menu background color.
            activeforeground: The text color of the entry under the pointer.
            activebackground: The background color of the entry under the pointer.
            activeborderwidth: The border width of the entry under the pointer, in pixels.
            disabledforeground: The text color of disabled entries.
            selectcolor: The indicator color of checkbutton / radiobutton entries.
            borderwidth (bd): The 3-D border width in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            tearoff: True adds a dashed line that tears the menu into a floating window.
            tearoffcommand: A callback invoked when the menu is torn off.
            postcommand: A callback invoked just before the menu is posted — use it to update entries lazily.
            title: The title shown on a torn-off menu.
            type: The menu flavor: "normal", "menubar", or "tearoff". Set when the menu is created; changing it later has no effect.
            cursor: The mouse cursor over the menu (see Cursors).
            takefocus: Whether the menu accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        activeforeground: str = ...,
        activebackground: str = ...,
        activeborderwidth: int = ...,
        disabledforeground: str = ...,
        selectcolor: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        tearoff: bool = ...,
        tearoffcommand: Callable[..., Any] = ...,
        postcommand: Callable[..., Any] = ...,
        title: str = ...,
        type: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
    ) -> Any: ...
    config = configure

class Text(AutoStyleMixin, _tkinterText):
    """Text is tkinter's multi-line text widget (tk.Text), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        font: str | Font = ...,
        wrap: str = ...,
        tabs: str = ...,
        tabstyle: str = ...,
        spacing1: int = ...,
        spacing2: int = ...,
        spacing3: int = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        selectforeground: str = ...,
        selectbackground: str = ...,
        inactiveselectbackground: str = ...,
        insertbackground: str = ...,
        insertwidth: int = ...,
        insertborderwidth: int = ...,
        insertontime: int = ...,
        insertofftime: int = ...,
        insertunfocussed: str = ...,
        blockcursor: bool = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        relief: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        selectborderwidth: int = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        undo: bool = ...,
        autoseparators: bool = ...,
        maxundo: int = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        exportselection: bool = ...,
        setgrid: bool = ...,
        startline: int = ...,
        endline: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
    ) -> None:
        """Text is tkinter's multi-line text widget (tk.Text), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (the default) paints the widget with the active theme and repaints it on a theme switch; False opts out, leaving tkinter's default appearance for you to style yourself. This is ttkbootstrap's one addition to the widget — everything below is native tk.
            font: The default font for the text.
            wrap: How lines that exceed the width wrap: "char", "word", or "none" (no wrap — scroll horizontally instead).
            tabs: Tab stops, as a list of distances (optionally each followed by "left"/"right"/"center"/"numeric").
            tabstyle: How tabs interact with the tabs list: "tabular" or "wordprocessor".
            spacing1: Extra vertical space above the first display line of each text line.
            spacing2: Extra vertical space between the display lines of a single wrapped line.
            spacing3: Extra vertical space below the last display line of each text line.
            foreground (fg): The text color.
            background (bg): The page (background) color.
            selectforeground: The text color within the selection.
            selectbackground: The background color of the selection.
            inactiveselectbackground: The selection background when the widget doesn't have focus (an empty string hides the selection when unfocused).
            insertbackground: The color of the blinking insert cursor.
            insertwidth: The width of the insert cursor, in pixels.
            insertborderwidth: The 3-D border width drawn around the insert cursor.
            insertontime: Milliseconds the cursor is shown per blink.
            insertofftime: Milliseconds the cursor is hidden per blink (0 disables blinking).
            insertunfocussed: How the cursor is drawn when the widget lacks focus: "none", "hollow", or "solid".
            blockcursor: True draws the insert cursor as a block over the next character rather than a thin bar.
            width: The requested width in characters (not pixels).
            height: The requested height in lines (not pixels).
            padx: Internal horizontal padding between the text and the border, in pixels.
            pady: Internal vertical padding between the text and the border, in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            borderwidth (bd): The width of the 3-D border, in pixels.
            selectborderwidth: The border width drawn around selected text.
            highlightthickness: The width of the focus highlight drawn around the widget.
            highlightcolor: The focus-highlight color when the widget has focus.
            highlightbackground: The focus-highlight color when the widget does not have focus.
            undo: True enables the built-in undo/redo stack.
            autoseparators: True auto-inserts undo boundaries as the user types.
            maxundo: The maximum number of undo steps to keep (-1 for unlimited).
            state: "normal" (editable) or "disabled" (read-only; the widget also ignores insert/delete while disabled).
            cursor: The mouse cursor shown over the widget (see Cursors).
            takefocus: Whether the widget accepts focus during keyboard traversal.
            exportselection: Whether a selection is exported to the X selection / clipboard.
            setgrid: True makes the containing window resize in whole character cells.
            startline: Restrict the widget to start at this line of the underlying store (used by peer widgets; None for the full range).
            endline: Restrict the widget to end at this line of the underlying store (used by peer widgets; None for the full range).
            xscrollcommand: A callback connecting the widget to a horizontal scrollbar.
            yscrollcommand: A callback connecting the widget to a vertical scrollbar.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        font: str | Font = ...,
        wrap: str = ...,
        tabs: str = ...,
        tabstyle: str = ...,
        spacing1: int = ...,
        spacing2: int = ...,
        spacing3: int = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        selectforeground: str = ...,
        selectbackground: str = ...,
        inactiveselectbackground: str = ...,
        insertbackground: str = ...,
        insertwidth: int = ...,
        insertborderwidth: int = ...,
        insertontime: int = ...,
        insertofftime: int = ...,
        insertunfocussed: str = ...,
        blockcursor: bool = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        relief: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        selectborderwidth: int = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        undo: bool = ...,
        autoseparators: bool = ...,
        maxundo: int = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        exportselection: bool = ...,
        setgrid: bool = ...,
        startline: int = ...,
        endline: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
    ) -> Any: ...
    config = configure

class Canvas(AutoStyleMixin, _tkinterCanvas):
    """Canvas is tkinter's drawing surface (tk.Canvas) — a 2-D area that holds items (lines, shapes, text, images, embedded widgets) you create, move, restyle, and delete by id or tag. It is themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        background: str = ...,
        bg: str = ...,
        width: int = ...,
        height: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        scrollregion: tuple[Any, ...] = ...,
        confine: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        xscrollincrement: int = ...,
        yscrollincrement: int = ...,
        selectbackground: str = ...,
        selectforeground: str = ...,
        selectborderwidth: int = ...,
        insertbackground: str = ...,
        insertwidth: int = ...,
        insertborderwidth: int = ...,
        insertontime: int = ...,
        insertofftime: int = ...,
        state: str = ...,
        closeenough: float = ...,
        offset: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
    ) -> None:
        """Canvas is tkinter's drawing surface (tk.Canvas) — a 2-D area that holds items (lines, shapes, text, images, embedded widgets) you create, move, restyle, and delete by id or tag. It is themed by ttkbootstrap.

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (default) paints the canvas with the active theme and repaints on a theme switch; False opts out. This is ttkbootstrap's one addition — everything below is native tk.
            background (bg): The surface color.
            width: The requested width in pixels.
            height: The requested height in pixels.
            borderwidth (bd): The 3-D border width in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            highlightthickness: The width of the focus highlight around the widget.
            highlightcolor: The focus-highlight color when the widget has focus.
            highlightbackground: The focus-highlight color when the widget does not have focus.
            scrollregion: The scrollable area as (left, top, right, bottom) in canvas coordinates.
            confine: Whether to keep the view inside scrollregion.
            xscrollcommand: A callback connecting the canvas to a horizontal scrollbar.
            yscrollcommand: A callback connecting the canvas to a vertical scrollbar.
            xscrollincrement: The step size for horizontal "unit" scrolling, in pixels.
            yscrollincrement: The step size for vertical "unit" scrolling, in pixels.
            selectbackground: The background of selected text within an editable text item.
            selectforeground: The foreground of selected text within an editable text item.
            selectborderwidth: The border width of the selection, in pixels.
            insertbackground: The color of the text insert cursor.
            insertwidth: The width of the insert cursor, in pixels.
            insertborderwidth: The border width of the insert cursor, in pixels.
            insertontime: The insert-cursor blink on-time, in milliseconds.
            insertofftime: The insert-cursor blink off-time, in milliseconds.
            state: The default item state: "normal", "disabled", or "hidden".
            closeenough: How near (in pixels) the pointer must be to count as "over" an item.
            offset: The origin for tiled stipple/fill patterns.
            cursor: The mouse cursor over the canvas (see Cursors).
            takefocus: Whether the canvas accepts keyboard focus.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        background: str = ...,
        bg: str = ...,
        width: int = ...,
        height: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        scrollregion: tuple[Any, ...] = ...,
        confine: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        xscrollincrement: int = ...,
        yscrollincrement: int = ...,
        selectbackground: str = ...,
        selectforeground: str = ...,
        selectborderwidth: int = ...,
        insertbackground: str = ...,
        insertwidth: int = ...,
        insertborderwidth: int = ...,
        insertontime: int = ...,
        insertofftime: int = ...,
        state: str = ...,
        closeenough: float = ...,
        offset: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
    ) -> Any: ...
    config = configure

class Listbox(AutoStyleMixin, _tkinterListbox):
    """Listbox is tkinter's list of selectable text lines (tk.Listbox), themed by ttkbootstrap. Lines are addressed by integer index (0-based) or the special index "end" / "active"."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        listvariable: Variable = ...,
        selectmode: str = ...,
        selectbackground: str = ...,
        selectforeground: str = ...,
        selectborderwidth: int = ...,
        activestyle: str = ...,
        exportselection: bool = ...,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        disabledforeground: str = ...,
        justify: str = ...,
        width: int = ...,
        height: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        setgrid: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
    ) -> None:
        """Listbox is tkinter's list of selectable text lines (tk.Listbox), themed by ttkbootstrap. Lines are addressed by integer index (0-based) or the special index "end" / "active".

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (default) paints the listbox with the active theme and repaints on a theme switch; False opts out.
            listvariable: A StringVar holding the list items as a Tcl list — keeps the widget and the variable in sync.
            selectmode: "browse" (single, default), "single", "multiple", or "extended" (click-drag / Shift / Ctrl ranges).
            selectbackground: The background color of selected lines.
            selectforeground: The text color of selected lines.
            selectborderwidth: The border width of selected lines, in pixels.
            activestyle: How the active line is marked: "underline", "dotbox", or "none".
            exportselection: Whether the selection is exported to the X selection / clipboard.
            font: The font for the lines.
            foreground (fg): The text color.
            background (bg): The surface color.
            disabledforeground: The text color when state is "disabled".
            justify: Line alignment: "left", "center", or "right".
            width: The requested width in characters (0 fits the content).
            height: The requested height in lines (0 fits the content).
            borderwidth (bd): The 3-D border width in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            highlightthickness: The width of the focus highlight around the widget.
            highlightcolor: The focus-highlight color when the widget has focus.
            highlightbackground: The focus-highlight color when the widget does not have focus.
            state: "normal" or "disabled".
            cursor: The mouse cursor (see Cursors).
            takefocus: Whether the listbox accepts keyboard focus during traversal.
            setgrid: Whether the window resizes in whole lines/characters.
            xscrollcommand: A callback connecting the listbox to a horizontal scrollbar.
            yscrollcommand: A callback connecting the listbox to a vertical scrollbar.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        listvariable: Variable = ...,
        selectmode: str = ...,
        selectbackground: str = ...,
        selectforeground: str = ...,
        selectborderwidth: int = ...,
        activestyle: str = ...,
        exportselection: bool = ...,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        disabledforeground: str = ...,
        justify: str = ...,
        width: int = ...,
        height: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        setgrid: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
    ) -> Any: ...
    config = configure

class TkFrame(AutoStyleMixin, _tkinterFrame):
    """TkFrame is tkinter's classic tk.Frame container, themed by ttkbootstrap and re-exported as ttk.TkFrame. It is a plain rectangular surface used to group and lay out other widgets. Prefer the ttk Frame for themed layout; reach for TkFrame only when you need a classic-tk option the ttk frame doesn't expose (background, highlightthickness, per-widget relief/borderwidth, an off-screen container)."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        background: str = ...,
        bg: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        class_: str = ...,
        container: bool = ...,
        visual: str = ...,
        colormap: str = ...,
        # Accepted spellings outside the documented surface.
        name: str = ...,
    ) -> None:
        """TkFrame is tkinter's classic tk.Frame container, themed by ttkbootstrap and re-exported as ttk.TkFrame. It is a plain rectangular surface used to group and lay out other widgets. Prefer the ttk Frame for themed layout; reach for TkFrame only when you need a classic-tk option the ttk frame doesn't expose (background, highlightthickness, per-widget relief/borderwidth, an off-screen container).

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (default) paints the frame with the active theme and repaints on a theme switch; False opts out.
            background (bg): The fill color of the frame.
            borderwidth (bd): The 3-D border width in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            highlightthickness: The width of the focus highlight drawn around the widget when it (or a child) has keyboard focus.
            highlightcolor: The focus-highlight color when the widget has focus.
            highlightbackground: The focus-highlight color when the widget does not have focus.
            width: The requested width in pixels. Ignored unless geometry propagation is turned off (pack_propagate(False) / grid_propagate(False)).
            height: The requested height in pixels. Ignored unless geometry propagation is turned off.
            padx: Internal horizontal padding between the border and the content, in pixels.
            pady: Internal vertical padding between the border and the content, in pixels.
            cursor: The mouse cursor over the frame (see Cursors).
            takefocus: Whether the frame accepts keyboard focus during traversal.
            class_: Constructor only. The widget class used for option-database lookups and bindtags.
            container: Constructor only. True makes the frame an embed target for a foreign application window.
            visual: Constructor only. The X visual. Rarely needed.
            colormap: Constructor only. The X colormap. Rarely needed.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        background: str = ...,
        bg: str = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
    ) -> Any: ...
    config = configure

class TkLabel(AutoStyleMixin, _tkinterLabel):
    """TkLabel is tkinter's classic tk.Label, themed by ttkbootstrap and re-exported as ttk.TkLabel. It displays a line or block of read-only text, an image, or both. Prefer the ttk Label for themed text; reach for TkLabel only when you need a classic-tk option the ttk label doesn't expose (a per-widget background/foreground, bitmap, activeforeground, disabledforeground)."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        autostyle: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        image: PhotoImage = ...,
        bitmap: str = ...,
        compound: str = ...,
        underline: int = ...,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        activeforeground: str = ...,
        activebackground: str = ...,
        disabledforeground: str = ...,
        justify: str = ...,
        anchor: str = ...,
        wraplength: int = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
    ) -> None:
        """TkLabel is tkinter's classic tk.Label, themed by ttkbootstrap and re-exported as ttk.TkLabel. It displays a line or block of read-only text, an image, or both. Prefer the ttk Label for themed text; reach for TkLabel only when you need a classic-tk option the ttk label doesn't expose (a per-widget background/foreground, bitmap, activeforeground, disabledforeground).

        Args:
            master: The parent widget.
            autostyle: Constructor only. True (default) paints the label with the active theme and repaints on a theme switch; False opts out.
            text: The string to display.
            textvariable: A StringVar whose value is shown and tracked live.
            image: An image to display in place of, or beside, the text.
            bitmap: A built-in bitmap to display instead of an image.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            font: The font for the text.
            foreground (fg): The text color.
            background (bg): The surface color.
            activeforeground: The text color while the label is active (e.g. under the pointer in a menu).
            activebackground: The surface color while the label is active.
            disabledforeground: The text color when state is "disabled".
            justify: Alignment of multi-line text: "left", "center", or "right".
            anchor: Where the content sits within any extra space: "n", "ne", "center", and so on.
            wraplength: The width, in pixels, at which text wraps to a new line (0 disables wrapping).
            width: The requested width in characters (0 fits the content).
            height: The requested height in lines (0 fits the content).
            padx: Internal horizontal padding around the content, in pixels.
            pady: Internal vertical padding around the content, in pixels.
            borderwidth (bd): The 3-D border width in pixels.
            relief: The border style: "flat", "raised", "sunken", "groove", "ridge", or "solid".
            highlightthickness: The width of the focus highlight around the widget.
            highlightcolor: The focus-highlight color when the widget has focus.
            highlightbackground: The focus-highlight color when the widget does not have focus.
            state: "normal", "active", or "disabled".
            cursor: The mouse cursor (see Cursors).
            takefocus: Whether the label accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        text: str = ...,
        textvariable: Variable = ...,
        image: PhotoImage = ...,
        bitmap: str = ...,
        compound: str = ...,
        underline: int = ...,
        font: str | Font = ...,
        foreground: str = ...,
        fg: str = ...,
        background: str = ...,
        bg: str = ...,
        activeforeground: str = ...,
        activebackground: str = ...,
        disabledforeground: str = ...,
        justify: str = ...,
        anchor: str = ...,
        wraplength: int = ...,
        width: int = ...,
        height: int = ...,
        padx: int = ...,
        pady: int = ...,
        borderwidth: int = ...,
        bd: int = ...,
        relief: str = ...,
        highlightthickness: int = ...,
        highlightcolor: str = ...,
        highlightbackground: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
    ) -> Any: ...
    config = configure

class Button(BootMixin, _ttkButton):
    """Button is the native ttk push button (ttk.Button), themed by ttkbootstrap — a clickable trigger that runs its command when pressed."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        default: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Button is the native ttk push button (ttk.Button), themed by ttkbootstrap — a clickable trigger that runs its command when pressed.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. The style — an accent color (primary, …, dark, neutral) optionally with a variant (outline, link, ghost). See Styling options.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the button; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the button into a square. Default False.
            text: The label shown on the button.
            textvariable: A StringVar whose value is shown as the label and tracked live.
            command: The function called when the button is pressed.
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the label, in pixels (a single value, or per-side).
            default: The default-button ring: "normal", "active", or "disabled".
            state: "normal" or "disabled". For finer control use the state method (see Capabilities).
            cursor: The mouse cursor over the button (see Cursors).
            takefocus: Whether the button accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        default: str = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Checkbutton(BootMixin, _ttkCheckbutton):
    """Checkbutton is the native ttk labeled on/off toggle (ttk.Checkbutton), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        variable: Variable = ...,
        onvalue: Any = ...,
        offvalue: Any = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Checkbutton is the native ttk labeled on/off toggle (ttk.Checkbutton), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the widget; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the widget into a square. Default False.
            text: The label shown beside the check.
            textvariable: A StringVar whose value is shown as the label and tracked live.
            variable: The variable that holds the check state.
            onvalue: The value written to variable when checked.
            offvalue: The value written to variable when unchecked.
            command: The function called when the checkbutton is *invoked* — clicked, or activated with Space.
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the label, in pixels (a single value, or per-side).
            state: "normal" or "disabled". For finer control use the state method (see Capabilities).
            cursor: The mouse cursor over the checkbutton (see Cursors).
            takefocus: Whether the checkbutton accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        variable: Variable = ...,
        onvalue: Any = ...,
        offvalue: Any = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Combobox(BootMixin, _ttkCombobox):
    """Combobox is the native ttk drop-down list combined with an editable text field (ttk.Combobox), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        values: list[Any] = ...,
        postcommand: Callable[..., Any] = ...,
        height: int = ...,
        show: str = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        width: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        # Accepted spellings outside the documented surface.
        background: str = ...,
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Combobox is the native ttk drop-down list combined with an editable text field (ttk.Combobox), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            textvariable: A StringVar bound to the field's contents.
            values: The list of choices shown in the drop-down.
            postcommand: A callback run just before the drop-down list is posted.
            height: The maximum number of rows shown in the drop-down before it scrolls.
            show: A character to display instead of the real text (e.g. "*" for a password field).
            justify: Text alignment: "left", "center", or "right".
            font: The font for the text.
            foreground: The text color.
            validate: When validation runs: "none", "focus", "focusin", "focusout", "key", or "all".
            validatecommand: The callback that validates a proposed value; returns a boolean.
            invalidcommand: The callback run when validatecommand returns false.
            state: "normal", "readonly", or "disabled".
            exportselection: Whether the selection is exported to the clipboard/X selection.
            cursor: The mouse cursor over the field (see Cursors).
            takefocus: Whether the field accepts keyboard focus during traversal.
            width: The requested width in characters.
            xscrollcommand: A callback connecting the field to a horizontal scrollbar.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        values: list[Any] = ...,
        postcommand: Callable[..., Any] = ...,
        height: int = ...,
        show: str = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        width: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        background: str = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Entry(BootMixin, _ttkEntry):
    """Entry is the native ttk single-line text field (ttk.Entry), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        show: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        width: int = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        # Accepted spellings outside the documented surface.
        background: str = ...,
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Entry is the native ttk single-line text field (ttk.Entry), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            textvariable: A StringVar bound to the field's contents.
            show: A character to display instead of the real text (e.g. "*" for a password field).
            validate: When validation runs: "none", "focus", "focusin", "focusout", "key", or "all".
            validatecommand: The callback that validates a proposed value; returns a boolean.
            invalidcommand: The callback run when validatecommand returns false.
            justify: Text alignment: "left", "center", or "right".
            font: The font for the text.
            foreground: The text color.
            width: The requested width in characters.
            state: "normal", "disabled", or "readonly".
            exportselection: Whether the selection is exported to the clipboard/X selection.
            cursor: The mouse cursor over the field (see Cursors).
            takefocus: Whether the field accepts keyboard focus during traversal.
            xscrollcommand: A callback connecting the field to a horizontal scrollbar.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        show: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        width: int = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        xscrollcommand: Callable[..., Any] = ...,
        background: str = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Frame(BootMixin, _ttkFrame):
    """Frame is the native ttk rectangular container for grouping and laying out other widgets (ttk.Frame), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        padding: int | tuple[Any, ...] = ...,
        borderwidth: int = ...,
        relief: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Frame is the native ttk rectangular container for grouping and laying out other widgets (ttk.Frame), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            padding: Extra space inside the frame's border, in pixels (a single value, or per-side).
            borderwidth: The width of the frame's border, in pixels.
            relief: The border decoration: "flat", "raised", "sunken", "solid", "ridge", or "groove".
            width: The requested width in pixels. Ignored unless geometry propagation is turned off.
            height: The requested height in pixels. Ignored unless geometry propagation is turned off.
            cursor: The mouse cursor over the frame (see Cursors).
            takefocus: Whether the frame accepts keyboard focus during traversal. .. _frame-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        padding: int | tuple[Any, ...] = ...,
        borderwidth: int = ...,
        relief: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Labelframe(BootMixin, _ttkLabelframe):
    """Labelframe is the native ttk frame with a caption drawn into its border (ttk.Labelframe), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        text: str = ...,
        labelwidget: Misc = ...,
        labelanchor: str = ...,
        underline: int = ...,
        padding: int | tuple[Any, ...] = ...,
        borderwidth: int = ...,
        relief: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Labelframe is the native ttk frame with a caption drawn into its border (ttk.Labelframe), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            text: The caption drawn into the border.
            labelwidget: A widget to use as the label in place of text.
            labelanchor: Where the caption sits on the border: "nw", "n", "ne", "en", "e", and so on.
            underline: The character index in text to underline (for a mnemonic), or -1.
            padding: Extra space inside the frame's border, in pixels (a single value, or per-side).
            borderwidth: The width of the frame's border, in pixels.
            relief: The border decoration: "flat", "raised", "sunken", "solid", "ridge", or "groove".
            width: The requested width in pixels. Ignored unless geometry propagation is turned off.
            height: The requested height in pixels. Ignored unless geometry propagation is turned off.
            cursor: The mouse cursor over the frame (see Cursors).
            takefocus: Whether the frame accepts keyboard focus during traversal. .. _labelframe-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        text: str = ...,
        labelwidget: Misc = ...,
        labelanchor: str = ...,
        underline: int = ...,
        padding: int | tuple[Any, ...] = ...,
        borderwidth: int = ...,
        relief: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Label(BootMixin, _ttkLabel):
    """Label is the native ttk widget that displays a line or block of read-only text, an image, or both (ttk.Label), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        background: str = ...,
        anchor: str = ...,
        justify: str = ...,
        wraplength: int = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        relief: str = ...,
        borderwidth: int = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Label is the native ttk widget that displays a line or block of read-only text, an image, or both (ttk.Label), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the widget; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the widget into a square. Default False.
            text: The text shown on the label.
            textvariable: A StringVar whose value is shown as the text and tracked live.
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            font: The font for the text.
            foreground: The text color.
            background: The label's background color.
            anchor: How content is positioned in extra space, e.g. "center", "w", "e".
            justify: Alignment for multi-line text: "left", "center", or "right".
            wraplength: The width, in pixels, at which text wraps to a new line.
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the content, in pixels (a single value, or per-side).
            relief: The border style, e.g. "flat", "raised", "sunken", "groove", "ridge".
            borderwidth: The width of the border, in pixels.
            state: "normal" or "disabled".
            cursor: The mouse cursor over the label (see Cursors).
            takefocus: Whether the label accepts keyboard focus during traversal. .. _label-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        background: str = ...,
        anchor: str = ...,
        justify: str = ...,
        wraplength: int = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        relief: str = ...,
        borderwidth: int = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Menubutton(BootMixin, _ttkMenubutton):
    """Menubutton is the native ttk button that pops up an attached menu (ttk.Menubutton), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        menu: Menu = ...,
        direction: str = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Menubutton is the native ttk button that pops up an attached menu (ttk.Menubutton), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the widget; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the widget into a square. Default False.
            text: The label shown on the button.
            textvariable: A StringVar whose value is shown as the label and tracked live.
            menu: The Menu widget shown when the button is pressed.
            direction: Where the menu pops up relative to the button: "above", "below", "left", "right", or "flush".
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the label, in pixels (a single value, or per-side).
            state: "normal" or "disabled". For finer control use the state method (see Capabilities).
            cursor: The mouse cursor over the menubutton (see Cursors).
            takefocus: Whether the menubutton accepts keyboard focus during traversal. .. _menubutton-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        menu: Menu = ...,
        direction: str = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Notebook(BootMixin, _ttkNotebook):
    """Notebook is the native ttk tabbed container that shows one child pane at a time (ttk.Notebook), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        padding: int | tuple[Any, ...] = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Notebook is the native ttk tabbed container that shows one child pane at a time (ttk.Notebook), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            padding: Extra space around the pane area, in pixels (a single value, or per-side).
            width: The requested width of the pane area, in pixels.
            height: The requested height of the pane area, in pixels.
            cursor: The mouse cursor over the notebook (see Cursors).
            takefocus: Whether the notebook accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        padding: int | tuple[Any, ...] = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Panedwindow(BootMixin, _ttkPanedwindow):
    """Panedwindow is the native ttk container that divides its space between children with draggable sashes (ttk.Panedwindow), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Panedwindow is the native ttk container that divides its space between children with draggable sashes (ttk.Panedwindow), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            orient: The layout direction of the panes: "horizontal" or "vertical".
            width: The requested width, in pixels.
            height: The requested height, in pixels.
            cursor: The mouse cursor over the panedwindow (see Cursors).
            takefocus: Whether the panedwindow accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        width: int = ...,
        height: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Progressbar(BootMixin, _ttkProgressbar):
    """Progressbar is the native ttk horizontal or vertical bar that shows progress (ttk.Progressbar), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        length: int = ...,
        mode: str = ...,
        maximum: float = ...,
        value: float = ...,
        variable: Variable = ...,
        phase: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Progressbar is the native ttk horizontal or vertical bar that shows progress (ttk.Progressbar), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            orient: The layout direction: "horizontal" or "vertical".
            length: The requested size along the long axis, in pixels.
            mode: "determinate" (tracks value) or "indeterminate" (animates back and forth).
            maximum: The value at which the bar is full.
            value: The current progress amount.
            variable: A DoubleVar/IntVar bound to value.
            phase: Read-only animation phase, useful for driving custom indeterminate styles.
            cursor: The mouse cursor over the progress bar (see Cursors).
            takefocus: Whether the progress bar accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        length: int = ...,
        mode: str = ...,
        maximum: float = ...,
        value: float = ...,
        variable: Variable = ...,
        phase: int = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Radiobutton(BootMixin, _ttkRadiobutton):
    """Radiobutton is the native ttk one-of-many selector that shares a variable with its siblings (ttk.Radiobutton), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        variable: Variable = ...,
        value: Any = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Radiobutton is the native ttk one-of-many selector that shares a variable with its siblings (ttk.Radiobutton), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the widget; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the widget into a square. Default False.
            text: The label shown beside the button.
            textvariable: A StringVar whose value is shown as the label and tracked live.
            variable: The variable shared by all radiobuttons in the group.
            value: The value written to variable when this button is selected.
            command: The function called when this button is *invoked* — clicked, or activated with Space.
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the label, in pixels (a single value, or per-side).
            state: "normal" or "disabled". For finer control use the state method (see Capabilities).
            cursor: The mouse cursor over the radiobutton (see Cursors).
            takefocus: Whether the radiobutton accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        variable: Variable = ...,
        value: Any = ...,
        command: Callable[..., Any] = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Scale(BootMixin, _ttkScale):
    """Scale is the native ttk slider for choosing a numeric value from a range (ttk.Scale), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        from_: float = ...,
        to: float = ...,
        value: float = ...,
        variable: Variable = ...,
        orient: str = ...,
        length: int = ...,
        command: Callable[..., Any] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Scale is the native ttk slider for choosing a numeric value from a range (ttk.Scale), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            from_: The value at one end of the scale's range.
            to: The value at the other end of the scale's range.
            value: The current value.
            variable: A DoubleVar (or IntVar) bound to the current value.
            orient: The layout direction: "horizontal" or "vertical".
            length: The slider's length in pixels.
            command: Called with the new value (as a string) whenever the slider moves.
            state: "normal" or "disabled".
            cursor: The mouse cursor over the scale (see Cursors).
            takefocus: Whether the scale accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        from_: float = ...,
        to: float = ...,
        value: float = ...,
        variable: Variable = ...,
        orient: str = ...,
        length: int = ...,
        command: Callable[..., Any] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Scrollbar(BootMixin, _ttkScrollbar):
    """Scrollbar is the native ttk scrollbar that drives another widget's view (ttk.Scrollbar), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        command: Callable[..., Any] = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Scrollbar is the native ttk scrollbar that drives another widget's view (ttk.Scrollbar), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            orient: The layout direction: "horizontal" or "vertical".
            command: The scrolled widget's xview/yview method, called when the user drags the thumb or clicks the trough/arrows.
            cursor: The mouse cursor over the scrollbar (see Cursors).
            takefocus: Whether the scrollbar accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        command: Callable[..., Any] = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Separator(BootMixin, _ttkSeparator):
    """Separator is the native ttk thin horizontal or vertical dividing line (ttk.Separator), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Separator is the native ttk thin horizontal or vertical dividing line (ttk.Separator), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            orient: The layout direction: "horizontal" or "vertical".
            cursor: The mouse cursor over the separator (see Cursors).
            takefocus: Whether the separator accepts keyboard focus during traversal. .. _separator-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        orient: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Sizegrip(BootMixin, _ttkSizegrip):
    """Sizegrip is the native ttk resize handle for the bottom-right corner of a window (ttk.Sizegrip), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Sizegrip is the native ttk resize handle for the bottom-right corner of a window (ttk.Sizegrip), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            cursor: The mouse cursor over the sizegrip (see Cursors).
            takefocus: Whether the sizegrip accepts keyboard focus during traversal. .. _sizegrip-styling:
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Spinbox(BootMixin, _ttkSpinbox):
    """Spinbox is the native ttk text field with up/down arrows for stepping through numeric or listed values (ttk.Spinbox), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        from_: float = ...,
        to: float = ...,
        increment: float = ...,
        values: list[Any] = ...,
        format: str = ...,
        wrap: bool = ...,
        command: Callable[..., Any] = ...,
        show: str = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        width: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        # Accepted spellings outside the documented surface.
        background: str = ...,
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Spinbox is the native ttk text field with up/down arrows for stepping through numeric or listed values (ttk.Spinbox), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            textvariable: A StringVar bound to the field's contents.
            from_: The minimum value in the numeric range.
            to: The maximum value in the numeric range.
            increment: The amount each arrow press steps the value.
            values: An explicit list of values to step through, instead of a numeric range.
            format: A printf-style format for the displayed value (e.g. "%.2f").
            wrap: Whether stepping past either end wraps around to the other.
            command: A callback run each time an arrow is pressed.
            show: A character to display instead of the real text (e.g. "*" for a password field).
            justify: Text alignment: "left", "center", or "right".
            font: The font for the text.
            foreground: The text color.
            validate: When validation runs: "none", "focus", "focusin", "focusout", "key", or "all".
            validatecommand: The callback that validates a proposed value; returns a boolean.
            invalidcommand: The callback run when validatecommand returns false.
            state: "normal", "readonly", or "disabled".
            exportselection: Whether the selection is exported to the clipboard/X selection.
            cursor: The mouse cursor over the field (see Cursors).
            takefocus: Whether the field accepts keyboard focus during traversal.
            width: The requested width in characters.
            xscrollcommand: A callback connecting the field to a horizontal scrollbar.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        textvariable: Variable = ...,
        from_: float = ...,
        to: float = ...,
        increment: float = ...,
        values: list[Any] = ...,
        format: str = ...,
        wrap: bool = ...,
        command: Callable[..., Any] = ...,
        show: str = ...,
        justify: str = ...,
        font: str | Font = ...,
        foreground: str = ...,
        validate: str = ...,
        validatecommand: Callable[..., Any] = ...,
        invalidcommand: Callable[..., Any] = ...,
        state: str = ...,
        exportselection: bool = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        width: int = ...,
        xscrollcommand: Callable[..., Any] = ...,
        background: str = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class Treeview(BootMixin, _ttkTreeview):
    """Treeview is the native ttk multi-column tree/table of items (ttk.Treeview), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None = ...,
        *,
        bootstyle: str = ...,
        columns: list[Any] = ...,
        displaycolumns: list[Any] = ...,
        show: str = ...,
        selectmode: str = ...,
        height: int = ...,
        padding: int | tuple[Any, ...] = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """Treeview is the native ttk multi-column tree/table of items (ttk.Treeview), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            columns: The identifiers of the data columns, beyond the implicit tree column.
            displaycolumns: Which columns to display, and in what order (or "#all").
            show: Which parts to show: "tree", "headings", or both.
            selectmode: "extended", "browse", or "none".
            height: The number of rows visible before scrolling.
            padding: Extra space around the contents, in pixels (a single value, or per-side).
            xscrollcommand: A callback connecting the tree to a horizontal scrollbar.
            yscrollcommand: A callback connecting the tree to a vertical scrollbar.
            cursor: The mouse cursor over the tree (see Cursors).
            takefocus: Whether the tree accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        columns: list[Any] = ...,
        displaycolumns: list[Any] = ...,
        show: str = ...,
        selectmode: str = ...,
        height: int = ...,
        padding: int | tuple[Any, ...] = ...,
        xscrollcommand: Callable[..., Any] = ...,
        yscrollcommand: Callable[..., Any] = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

class OptionMenu(BootMixin, _ttkOptionMenu):
    """OptionMenu is the native ttk menubutton preconfigured with a menu of options that tracks the chosen one in a variable (ttk.OptionMenu), themed by ttkbootstrap."""
    def __init__(
        self,
        master: Misc | None,
        variable: Variable | None,
        default: str | None = ...,
        *values: str,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        menu: Menu = ...,
        direction: str = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        # Accepted spellings outside the documented surface.
        class_: str = ...,
        name: str = ...,
        style: str = ...,
    ) -> None:
        """OptionMenu is the native ttk menubutton preconfigured with a menu of options that tracks the chosen one in a variable (ttk.OptionMenu), themed by ttkbootstrap.

        Args:
            master: The parent widget.
            variable: The variable holding the selected value.
            default: The value to show before a choice is made.
            *values: The choices offered in the dropdown.
            bootstyle: Constructor keyword. An accent color, optionally with a variant. See Styling options for the available styles.
            icon: Constructor keyword. A Bootstrap Icons glyph name (e.g. "gear-fill") shown on the widget; theme-aware — it follows the foreground color and states. See the Icons guide.
            icon_size: Constructor keyword. The glyph size in pixels (scaled for high-DPI).
            icon_only: Constructor keyword. Show only the glyph (hide the text) and pad the widget into a square. Default False.
            text: The label shown on the button.
            textvariable: A StringVar whose value is shown as the label and tracked live.
            menu: The Menu widget shown when the button is pressed.
            direction: Where the menu pops up relative to the button: "above", "below", "left", "right", or "flush".
            image: An image to display in place of, or beside, the text.
            compound: How text and image are combined: "none", "left", "right", "top", "bottom", or "center".
            underline: The character index to underline (for a keyboard mnemonic), or -1.
            width: The requested width in characters (negative sets a minimum).
            padding: Extra space around the label, in pixels (a single value, or per-side).
            state: "normal" or "disabled". For finer control use the state method (see Capabilities).
            cursor: The mouse cursor over the menubutton (see Cursors).
            takefocus: Whether the menubutton accepts keyboard focus during traversal.
        """

    def configure(
        self,
        cnf: Any = ...,
        *,
        bootstyle: str = ...,
        icon: str = ...,
        icon_size: int = ...,
        icon_only: bool = ...,
        text: str = ...,
        textvariable: Variable = ...,
        menu: Menu = ...,
        direction: str = ...,
        image: PhotoImage = ...,
        compound: str = ...,
        underline: int = ...,
        width: int = ...,
        padding: int | tuple[Any, ...] = ...,
        state: str = ...,
        cursor: str = ...,
        takefocus: bool = ...,
        style: str = ...,
    ) -> Any: ...
    config = configure

LabelFrame = Labelframe
